image: macos


clone_depth: 50



environment:
  script: .



artifacts:
  - path: '**\*asm2c'
  - path: '**\*.c'
  - path: '**\*.h'
  


build_script:

  - sh: |
      export DIR=$APPVEYOR_BUILD_FOLDER
      cd $DIR


      git submodule update --init --recursive


      swift -version


      cd $DIR
      swift build

      .build/debug/asm2c $DIR/P.asm $DIR/Resources
