# image: ubuntu
image: macos


clone_depth: 1



environment:
  script: .



artifacts:
  - path: '**\*libretro.dylib'
  


build_script:

  - sh: |
      export DIR=$APPVEYOR_BUILD_FOLDER
      cd $DIR


      git submodule update --init --recursive


      # wget https://swift.org/builds/swift-5.1.3-release/ubuntu1804/swift-5.1.3-RELEASE/swift-5.1.3-RELEASE-ubuntu18.04.tar.gz
      # tar -xvzf swift-5.1.3-RELEASE*
      # export PATH=$DIR/swift-5.1.3-RELEASE-ubuntu18.04:$PATH
      # export PATH=$DIR/swift-5.1.3-RELEASE-ubuntu18.04/usr/bin:$PATH

      swift -version


      cd $DIR
      swift build
