image: macos


clone_depth: 50



environment:
  script: .



artifacts:
  - path: '**\*asm2c'
  


build_script:

  - sh: |
      export DIR=$APPVEYOR_BUILD_FOLDER
      cd $DIR


      git submodule update --init --recursive


      swift -version


      cd $DIR
      swift build

      cp .build/debug/asm2c Resources
      cd Resources
      asm2c p.asm .
